### ISSUE TITLE
[Feature] English restriction to be added

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/classroom-monitor-bot#36]
People sometimes start talking in their native language which is not understood by all and hence suppresses the aim of inclusiveness. The bot should have some feature to restrict use of external words.

**Comment by nikhilisaac** [comment]
you want a new bot or want this functionality added to an existing bot @kaiwalyakoparkar

**Comment by juuz0** [comment]
Would a regex solution be allowed?
If yes, I would like to work on it!

**Comment by juuz0** [comment]
I'm not sure how that's achievable

I only see two ways,

1. Do a regex search for **only** English characters, numbers and special characters. 
This wouldn't really be an optimal solution since a lot of Hindi/Urdu users write their language using English letters on platforms

2. Use an API like wordnik to search within English dictionaries and if failed, tell the user to edit their message. 
This looks good while testing for only English but typos like writing **Helo** instead of **Hello** would also be classified as non English. 

Which is better between the two or is there some other way too?

**Comment by nikhilisaac** [comment]
languagelayer api should also work  @juuz0 
the first option will be too cumbersome and most of the violations will go undetected
 another suggestion is to add a translation function which may help people who have trouble communicating in english but I dont know whether it will be able to do that for Hindi words written in English script

**Comment by kaiwalyakoparkar** [comment]
Awesome thoughts @juuz0 and @nikhilisaac :boom: Should we create a discussion and discuss this as this is an essential feature for the bot.

**Comment by nikhilisaac** [comment]
> Awesome thoughts @juuz0 and @nikhilisaac 💥 Should we create a discussion and discuss this as this is an essential feature for the bot.

sure

**Comment by kaiwalyakoparkar** [comment]
Awesome @nikhilisaac Would you like to go ahead and create one discussion (If not opened already)? :smile:

**Comment by ctnkaan** [comment]
PR #65 kind of solves this issue.
